"""P2P1 Taylor-Hood element on a small Neo-Hooke cantilever, static solver, one rank.

The mesh is generated by helpers.cantilever rather than shipped, clamped at x = 0 and bent
by a pressure on its top face. Every length, the shear modulus and the bulk modulus are O(1),
so the displacement, coupling and constraint blocks of the Jacobian have comparable magnitude.
On a millimetre mesh in SI units those blocks differ by many decades, and a relative Jacobian
check would see nothing but the displacement block.
"""
import re
import shutil
from pathlib import Path

import numpy as np
import pytest

from helpers.cantilever import SHAPE, node, write_mesh
from helpers.compare import read_vtu_point_field, read_vtu_points
from helpers.run import assert_no_petsc_error, assert_refused, run_binary

FIXTURE = Path(__file__).parent / "fixtures" / "p2p1_cantilever.xml"
ROBIN_FIXTURE = Path(__file__).parent / "fixtures" / "p2p1_cantilever_robin.xml"
DYNAMIC_FIXTURE = Path(__file__).parent / "fixtures" / "p2p1_cantilever_dynamic.xml"

# T10 local nodes 5-10 sit on the edges (1,2), (2,3), (1,3), (1,4), (2,4), (3,4).
T10_EDGES = ((0, 1), (1, 2), (0, 2), (0, 3), (1, 3), (2, 3))


def _clamped_dofs():
    """Displacement unknowns of the clamped face x = 0; on one rank, 3 * node + component."""
    return {3 * (node((0, j, k)) - 1) + c
            for j in range(SHAPE[1]) for k in range(SHAPE[2]) for c in range(3)}


# Parameters of each law with every modulus O(1), for the reasons given above. The fixtures have
# no bases file, so the fibre direction is x, along the cantilever, which bending stretches and
# compresses. Holzapfel keeps its default smoothed Heavyside switch.
MATERIALS = {
    "NeoHooke": "<NeoHooke><a>1</a><k>{kappa}</k></NeoHooke>",
    "Holzapfel": "<Holzapfel><a>1</a><b>1</b><af>1</af><bf>1</bf><as>0.5</as><bs>1</bs>"
                 "<afs>0.3</afs><bfs>1</bfs><kappa>{kappa}</kappa></Holzapfel>",
    "Guccione": "<Guccione><C>1</C><bf>8</bf><bt>2</bt><bfs>4</bfs><K>{kappa}</K></Guccione>",
    "MooneyRivlin": "<MooneyRivlin><C10>1</C10><B>{kappa}</B></MooneyRivlin>",
    "Usyk": "<Usyk><a>1</a><bff>8</bff><bss>2</bss><bnn>2</bnn><bfs>4</bfs><bfn>4</bfn><bns>2</bns>"
            "<k>{kappa}</k></Usyk>",
}


def _run(binary, cm_env, wd, element_type="T10P1", kappa=100, material="NeoHooke", solver=None,
         env=None, check=True, ranks=None, fixture=FIXTURE, replace=()):
    """Stage mesh and settings into wd, run on ranks MPI ranks (serially if None), return (process, vtu directory).
    solver replaces the Static solver of the fixture; None keeps the fixture's own. replace holds further
    (old, new) substitutions of the settings text."""
    (wd / "tetgen").mkdir()
    write_mesh(wd / "tetgen")
    (wd / "Results").mkdir()
    text, n = re.subn(r"<NeoHooke>.*?</NeoHooke>", MATERIALS[material].format(kappa=kappa),
                      fixture.read_text(), flags=re.DOTALL)
    assert n == 1, f"{fixture.name}: cannot substitute the NeoHooke parameters"
    substitutions = [("<Type>T10P1</Type>", f"<Type>{element_type}</Type>"),
                     ("<Type>NeoHooke</Type>", f"<Type>{material}</Type>")]
    if solver:
        substitutions.append(("<Type>Static</Type>", f"<Type>{solver}</Type>"))
    substitutions += replace
    for old, new in substitutions:
        assert text.count(old) == 1, f"{fixture.name}: cannot substitute {old}"
        text = text.replace(old, new)
    (wd / fixture.name).write_text(text)
    proc = run_binary(binary("CardioMechanics"), ["-settings", fixture.name],
                      cwd=wd, env=env or cm_env, timeout=600, check=check, np=ranks)
    if check:
        assert "SIMULATION FAILED" not in proc.stdout, f"{element_type} kappa={kappa}\n{proc.stdout[-2000:]}"
    return proc, wd / "Results" / "cantilever_vtu"


def _last_vtu(vtu_dir):
    return max(vtu_dir.glob("cantilever.*.vtu"), key=lambda p: int(p.stem.split(".")[1]))


def _final_points(vtu_dir):
    return read_vtu_points(_last_vtu(vtu_dir))


def _peak_displacement(vtu_dir):
    _, pts = _final_points(vtu_dir)
    _, ref = read_vtu_points(vtu_dir / "cantilever.0.vtu")
    return np.linalg.norm(pts - ref, axis=1).max()


def test_unknown_element_type_lists_p2p1(binary, cm_env, tmp_path):
    proc, _ = _run(binary, cm_env, tmp_path, element_type="T10Q1", check=False)
    assert proc.returncode != 0, f"expected a non-zero exit\n{proc.stdout[-2000:]}"
    assert "T10P1" in proc.stdout + proc.stderr, (proc.stdout + proc.stderr)[-2000:]


@pytest.mark.parametrize("material", ["MooneyRivlin", "Usyk"])
def test_p2p1_refuses_material_without_mixed_formulation(binary, cm_env, tmp_path, material):
    proc, _ = _run(binary, cm_env, tmp_path, material=material, check=False)
    assert_refused(proc, material, "T10P1")


def test_active_stress_estimator_refuses_p2p1(binary, cm_env, tmp_path):
    """The estimator differentiates nodal forces with respect to element tension, which has no
    counterpart for the pressure field."""
    proc, _ = _run(binary, cm_env, tmp_path, solver="ActiveStressEstimator", check=False)
    assert_refused(proc, "Active Stress Estimator", "T10P1")


def _active_tension(measure):
    """Settings substitution for a fibre tension ramped to 0.3 over the run, with the top face unloaded."""
    return [("<TensionMax>0</TensionMax>",
             "<TensionMax>0.3</TensionMax><TensionModel>FromFunction</TensionModel>"
             "<FromFunction><Type>Linear</Type><StartTime>0</StartTime><StopTime>1</StopTime></FromFunction>"
             f"<ActiveTensionMeasure>{measure}</ActiveTensionMeasure>"),
            ("<Amplitude>0.003</Amplitude>", "<Amplitude>0</Amplitude>")]


def test_unknown_active_tension_measure_is_refused(binary, cm_env, tmp_path):
    proc, _ = _run(binary, cm_env, tmp_path, replace=_active_tension("Cauchy"), check=False)
    assert_refused(proc, "ActiveTensionMeasure", "Cauchy")


def test_pk2_active_tension_shortens_fibres_less_than_nominal(binary, cm_env, tmp_path):
    """A shortening fibre has stretch below one, so the nominal measure's PK2 stress, tension over
    stretch, exceeds the constant PK2 stress of the same tension."""
    pytest.importorskip("meshio")
    shortening = {}
    for measure in ("Nominal", "PK2"):
        wd = tmp_path / measure
        wd.mkdir()
        _, vtu_dir = _run(binary, cm_env, wd, replace=_active_tension(measure))
        _, pts = _final_points(vtu_dir)
        _, ref = read_vtu_points(vtu_dir / "cantilever.0.vtu")
        shortening[measure] = ref[:, 0].max() - pts[:, 0].max()
    assert shortening["PK2"] > 1e-2, f"fibres barely shortened: {shortening}"
    assert shortening["PK2"] < shortening["Nominal"], f"PK2 shortened at least as much as nominal: {shortening}"


def test_p2p1_static_run_converges(binary, cm_env, tmp_path):
    pytest.importorskip("meshio")
    _, vtu_dir = _run(binary, cm_env, tmp_path)
    _, pts = _final_points(vtu_dir)
    _, ref = read_vtu_points(vtu_dir / "cantilever.0.vtu")
    deflection = np.abs(pts - ref).max()
    assert deflection > 1e-2, f"cantilever barely moved: max displacement {deflection:.3e}"


DYNAMIC_STEPS = 4            # StopTime / TimeStep of the dynamic fixture, one export per step
MIN_TENSION_EFFECT = 0.05    # relative change of the peak displacement


@pytest.mark.parametrize("consistent_mass", ["true", "false"], ids=["consistent_mass", "lumped_mass"])
def test_p2p1_generalized_alpha_run_completes(binary, cm_env, tmp_path, consistent_mass):
    """Both mass matrices span the displacement unknowns alone, so the pressure meets neither a mass
    nor a zero diagonal. The run is compared with one without active tension, since the load alone
    would move the cantilever too."""
    pytest.importorskip("meshio")
    peaks = {}
    for tension in ("0.05", "0"):
        wd = tmp_path / f"tension_{tension}"
        wd.mkdir()
        proc, vtu_dir = _run(binary, cm_env, wd, fixture=DYNAMIC_FIXTURE, replace=[
            ("<ConsistentMassMatrix>true</ConsistentMassMatrix>",
             f"<ConsistentMassMatrix>{consistent_mass}</ConsistentMassMatrix>"),
            ("<TensionMax>0.05</TensionMax>", f"<TensionMax>{tension}</TensionMax>")])
        assert_no_petsc_error(proc.stdout + proc.stderr)
        assert _last_vtu(vtu_dir).name == f"cantilever.{DYNAMIC_STEPS}.vtu", \
            f"TensionMax={tension}: run stopped before its stop time"
        peaks[tension] = _peak_displacement(vtu_dir)
    assert peaks["0.05"] > 1e-2, f"cantilever barely moved: peak displacement {peaks['0.05']:.3e}"
    assert abs(peaks["0.05"] - peaks["0"]) > MIN_TENSION_EFFECT * peaks["0"], \
        f"active tension barely acts: peak displacement {peaks['0.05']:.4e} with, {peaks['0']:.4e} without"


def test_p2p1_exports_pressure_linear_along_edges(binary, cm_env, tmp_path):
    """Mid-edge nodes carry no pressure unknown. The value exported there is the linear field at
    the edge midpoint, the mean of its two vertices, so a viewer interpolating the quadratic cell
    reproduces the linear field instead of dipping towards zero on every edge."""
    meshio = pytest.importorskip("meshio")
    _, vtu_dir = _run(binary, cm_env, tmp_path)
    mesh = meshio.read(str(_last_vtu(vtu_dir)))
    p = np.asarray(mesh.point_data["Pressure"]).ravel()
    assert np.abs(p).max() > 0, "exported pressure is zero everywhere"

    cells = mesh.cells_dict["tetra10"]     # VTK orders the mid-edge nodes as T10_EDGES
    expected = np.stack([(p[cells[:, a]] + p[cells[:, b]]) / 2 for a, b in T10_EDGES], axis=1)
    d = np.abs(p[cells[:, 4:]] - expected)
    tol = 1e-12 * np.abs(p).max()
    if d.max() > tol:
        c, k = np.unravel_index(np.argmax(d), d.shape)
        raise AssertionError(f"mid-edge pressure is not the mean of its vertices beyond {tol:.1e}: "
                             f"node {cells[c, 4 + k]} has {p[cells[c, 4 + k]]:.6e}, expected {expected[c, k]:.6e}")


# Barycentric coordinates of the four quadrature points of CBElementSolidT10: point q lies at
# ALPHA on vertex q and at BETA on the other three, each weighing a quarter of the element.
ALPHA, BETA = (5 + 3 * np.sqrt(5)) / 20, (5 - np.sqrt(5)) / 20
# The VTU points are single precision, so J - 1, of order 1e-3 here, keeps about four digits:
# observed 6e-4 of the peak. A sign or scale error in the exported pressure is of order one.
BALANCE_RTOL = 5e-3
# The first generalized-alpha step deforms far less, J - 1 about 2e-6, and float32 rounding alone
# moves the misfit there between 4e-3 and 1.2e-2. Pairing the intermediate geometry with p_n+1,
# the error the test targets, misses by 0.11 (last step) to 0.33 (first step).
DYNAMIC_BALANCE_RTOL = 3e-2


def _t10_gradients(L):
    """Derivatives of the ten T10 shape functions, in VTK node order, with respect to L1, L2, L3
    at barycentric point L."""
    dL = np.zeros((10, 4))          # with respect to L0..L3
    for i in range(4):
        dL[i, i] = 4 * L[i] - 1
    for k, (i, j) in enumerate(T10_EDGES):
        dL[4 + k, i], dL[4 + k, j] = 4 * L[j], 4 * L[i]
    return dL[:, 1:] - dL[:, :1]    # L0 = 1 - L1 - L2 - L3


def _assert_constraint_holds(ref, cur, cells, pressure, kappa, where, rtol=BALANCE_RTOL):
    """Rebuild the constraint of every vertex a, int N_a (J - 1 - p/kappa) dV = 0, on the element
    quadrature rule from reference points ref, current points cur and nodal pressures."""
    p = pressure[cells[:, :4]]
    pressure_term, volume_term = np.zeros(len(cur)), np.zeros(len(cur))
    for q in range(4):
        L = np.full(4, BETA)
        L[q] = ALPHA
        dN = _t10_gradients(L)
        dV = np.linalg.det(np.einsum("cai,ak->cik", ref[cells], dN)) / 24
        dv = np.linalg.det(np.einsum("cai,ak->cik", cur[cells], dN)) / 24
        np.add.at(pressure_term, cells[:, :4], (dV * (p @ L))[:, None] * L)
        np.add.at(volume_term, cells[:, :4], kappa * (dv - dV)[:, None] * L)

    d = np.abs(pressure_term - volume_term)
    tol = rtol * np.abs(pressure_term).max()
    i = int(np.argmax(d))
    assert d[i] <= tol, (f"{where}, vertex {i}: int N p dV = {pressure_term[i]:.6e} but kappa int N (J-1) dV = "
                         f"{volume_term[i]:.6e}, beyond {tol:.1e}")


def test_p2p1_pressure_satisfies_constraint(binary, cm_env, tmp_path):
    """The constraint holds to solver precision for the solved pressure, so rebuilt from the
    exported geometry and pressure it pins the sign and scale of the export, which the mid-edge
    test cannot."""
    meshio = pytest.importorskip("meshio")
    kappa = 100
    _, vtu_dir = _run(binary, cm_env, tmp_path, kappa=kappa)
    ref = meshio.read(str(vtu_dir / "cantilever.0.vtu"))     # unloaded at t = 0
    cur = meshio.read(str(_last_vtu(vtu_dir)))
    _assert_constraint_holds(ref.points, cur.points, cur.cells_dict["tetra10"],
                             np.asarray(cur.point_data["Pressure"]).ravel(), kappa, "end of the run")


RHO_INF = float(re.search(r"<RhoInf>(.*?)</RhoInf>", DYNAMIC_FIXTURE.read_text()).group(1))
ALPHA_F = RHO_INF / (1 + RHO_INF)   # Chung-Hulbert


def test_p2p1_generalized_alpha_constraint_holds_at_intermediate_configuration(binary, cm_env, tmp_path):
    """Generalized-alpha evaluates the whole residual at d_n+1-alphaF, the constraint included,
    with the pressure interpolated between time levels exactly like the displacement. Rebuilt from
    consecutive frames, the constraint therefore holds at that level. Holding it at the end of the
    step instead, or pairing the intermediate geometry with p_n+1, misses by about alphaF times the
    pressure change over a step, a third of the pressure in the first step here."""
    meshio = pytest.importorskip("meshio")
    kappa = 100
    _, vtu_dir = _run(binary, cm_env, tmp_path, kappa=kappa, fixture=DYNAMIC_FIXTURE)
    frames = [meshio.read(str(vtu_dir / f"cantilever.{n}.vtu")) for n in range(DYNAMIC_STEPS + 1)]
    cells = frames[0].cells_dict["tetra10"]

    def intermediate(old, new):
        return (1 - ALPHA_F) * np.asarray(new, dtype=float) + ALPHA_F * np.asarray(old, dtype=float)

    for n in range(DYNAMIC_STEPS):
        old, new = frames[n], frames[n + 1]
        _assert_constraint_holds(frames[0].points, intermediate(old.points, new.points), cells,
                                 intermediate(old.point_data["Pressure"], new.point_data["Pressure"]).ravel(),
                                 kappa, f"step {n + 1}", DYNAMIC_BALANCE_RTOL)


def test_displacement_only_exports_no_pressure(binary, cm_env, tmp_path):
    meshio = pytest.importorskip("meshio")
    _, vtu_dir = _run(binary, cm_env, tmp_path, element_type="T10")
    assert "Pressure" not in meshio.read(str(_last_vtu(vtu_dir))).point_data


NP = 4
DEFORM_RTOL, DEFORM_ATOL = 1e-4, 1e-8     # as for the benchmark goldens
PRESSURE_RTOL = 1e-4                      # absolute tolerance scaled by the peak pressure


def _assert_parallel_matches_serial(binary, cm_env, tmp_path, fixture):
    """Run fixture serially and at NP ranks, assert the final shapes and pressures agree, return the
    serial vtu directory."""
    pytest.importorskip("meshio")
    if shutil.which("mpirun") is None:
        pytest.skip("mpirun not found")
    points, vtu_dirs = {}, {}
    for ranks in (None, NP):
        wd = tmp_path / f"np{ranks or 1}"
        wd.mkdir(parents=True)
        proc, vtu_dirs[ranks] = _run(binary, cm_env, wd, ranks=ranks, fixture=fixture)
        assert_no_petsc_error(proc.stdout + proc.stderr)
        points[ranks] = _final_points(vtu_dirs[ranks])

    (pid, serial), (pid_parallel, parallel) = points[None], points[NP]
    assert np.array_equal(pid, pid_parallel), "point ordering differs between serial and parallel"
    if not np.allclose(parallel, serial, rtol=DEFORM_RTOL, atol=DEFORM_ATOL):
        d = np.linalg.norm(parallel - serial, axis=1)
        i = int(np.argmax(d))
        raise AssertionError(
            f"{fixture.name}: np={NP} differs from serial beyond rtol={DEFORM_RTOL} atol={DEFORM_ATOL}: "
            f"node PointID={int(pid[i])} parallel={parallel[i]} serial={serial[i]} |delta|={d[i]:.3e}")

    # Each rank writes the pressures of its own elements, including nodes owned by another rank.
    _, p_serial = read_vtu_point_field(_last_vtu(vtu_dirs[None]), "Pressure")
    _, p_parallel = read_vtu_point_field(_last_vtu(vtu_dirs[NP]), "Pressure")
    atol = PRESSURE_RTOL * np.abs(p_serial).max()
    if not np.allclose(p_parallel, p_serial, rtol=PRESSURE_RTOL, atol=atol):
        i = int(np.argmax(np.abs(p_parallel - p_serial)))
        raise AssertionError(
            f"{fixture.name}: np={NP} pressure differs from serial beyond rtol={PRESSURE_RTOL} atol={atol:.3e}: "
            f"node PointID={int(pid[i])} parallel={p_parallel[i]:.6e} serial={p_serial[i]:.6e}")
    return vtu_dirs[None]


@pytest.mark.mpi
def test_p2p1_parallel_matches_serial(binary, cm_env, tmp_path):
    """Every rank but the first shifts its displacement unknowns by the pressure unknowns of the
    ranks before it, and needs the pressures of vertices it ghosts, so a parallel run that writes
    a global index without the offset, or misses a ghost, departs from the serial one."""
    _assert_parallel_matches_serial(binary, cm_env, tmp_path, FIXTURE)


@pytest.mark.mpi
def test_p2p1_generalized_alpha_parallel_matches_serial(binary, cm_env, tmp_path):
    """The mass and damping matrices are laid out like the nodes, the unknowns like each rank's
    displacements followed by its pressures, so on every rank but the first adding one to the other
    needs the translation between the two layouts."""
    _assert_parallel_matches_serial(binary, cm_env, tmp_path, DYNAMIC_FIXTURE)


MIN_ROBIN_EFFECT = 0.05     # relative change of the peak displacement


@pytest.mark.mpi
def test_p2p1_robin_boundary_parallel_matches_serial(binary, cm_env, tmp_path):
    """A Robin boundary adds its forces by global node rather than through the element mapping,
    from surface elements on every rank."""
    robin = _peak_displacement(_assert_parallel_matches_serial(binary, cm_env, tmp_path / "robin", ROBIN_FIXTURE))
    (tmp_path / "free").mkdir()
    _, vtu_dir = _run(binary, cm_env, tmp_path / "free")
    free = _peak_displacement(vtu_dir)
    assert abs(robin - free) > MIN_ROBIN_EFFECT * free, \
        f"Robin boundary barely acts: peak displacement {robin:.4e} with, {free:.4e} without"


JACOBIAN_THRESHOLD = 1e-6


def _jacobian_differences(view_file):
    """Non-zero (row, column, value) entries of the hand-coded minus finite-difference Jacobian.

    PETSc writes the hand-coded, the finite-difference and the thresholded difference matrix,
    in that order, and rewrites the file at every Jacobian evaluation, so it holds the last one.
    """
    sections = view_file.read_text().split("Mat Object:")[1:]
    assert len(sections) == 3, f"{view_file.name}: expected 3 matrices, found {len(sections)}"
    entries = []
    for line in sections[2].splitlines():
        m = re.match(r"\s*row (\d+):(.*)", line)
        if m:
            entries += [(int(m.group(1)), int(c), float(v))
                        for c, v in re.findall(r"\((\d+), ([^)]+)\)", m.group(2)) if float(v) != 0]
    return entries


@pytest.mark.parametrize("fixture", [FIXTURE, DYNAMIC_FIXTURE], ids=["static", "generalized_alpha"])
def test_p2p1_jacobian_matches_finite_differences(binary, cm_env, tmp_path, fixture):
    """Every Jacobian block, coupling and constraint included, against PETSc's finite differences.
    Under generalized-alpha that includes the mass and damping terms and the (1 - alphaF) factor
    of both fields at the intermediate configuration.

    kappa = 1 keeps the -1/kappa constraint block well above the threshold. Entries in clamped
    rows and columns are excluded: the hand-coded Jacobian replaces those rows by the identity and
    drops those columns, because a clamped increment is zero, whereas finite differences perturb
    clamped nodes like any other.
    """
    view = tmp_path / "jacobian.txt"
    env = dict(cm_env, PETSC_OPTIONS=f"-snes_test_jacobian {JACOBIAN_THRESHOLD} "
                                     f"-snes_test_jacobian_view ascii:{view}")
    _run(binary, cm_env, tmp_path, kappa=1, env=env, fixture=fixture)
    clamped = _clamped_dofs()
    wrong = [e for e in _jacobian_differences(view) if e[0] not in clamped and e[1] not in clamped]
    if wrong:
        row, col, value = max(wrong, key=lambda e: abs(e[2]))
        raise AssertionError(f"{len(wrong)} Jacobian entries differ beyond {JACOBIAN_THRESHOLD}, "
                             f"worst at row {row} column {col}: {value:.3e}")


# Eliminating the pressure pointwise from the perturbed constraint gives back Neo-Hooke's
# volumetric energy kappa/2 (J-1)^2, so at any kappa both elements model the same material and
# differ only in how the discretization carries the volumetric response. As kappa -> 0 that
# response vanishes and the two coincide; as kappa grows T10 locks and the gap opens up to its
# locking error. Observed gap over peak displacement: 6e-4, 2e-2, 6e-2, 8e-2 at kappa = 1, 10,
# 100, 1000.
KAPPA_SWEEP = (1, 10, 100, 1000)
MAX_GAP_AT_SMALLEST_KAPPA = 2e-3     # relative to the peak displacement


def _gap_to_t10(binary, cm_env, tmp_path, kappa, material="NeoHooke"):
    """Largest P2P1-T10 node distance over the T10 peak displacement, and the PointID it occurs at."""
    vtu_dirs = {}
    for element_type in ("T10", "T10P1"):
        wd = tmp_path / f"{material}_{element_type}_{kappa}"
        wd.mkdir()
        _, vtu_dirs[element_type] = _run(binary, cm_env, wd, element_type=element_type, kappa=kappa,
                                         material=material)
    pid, t10 = _final_points(vtu_dirs["T10"])
    _, p2p1 = _final_points(vtu_dirs["T10P1"])
    _, ref = read_vtu_points(vtu_dirs["T10"] / "cantilever.0.vtu")
    d = np.linalg.norm(p2p1 - t10, axis=1)
    i = int(np.argmax(d))
    return d[i] / np.linalg.norm(t10 - ref, axis=1).max(), int(pid[i])


def test_p2p1_approaches_t10_as_kappa_decreases(binary, cm_env, tmp_path):
    pytest.importorskip("meshio")
    gaps = [(kappa, *_gap_to_t10(binary, cm_env, tmp_path, kappa)) for kappa in KAPPA_SWEEP]

    report = ", ".join(f"kappa={k}: {g:.2e} at PointID={n}" for k, g, n in gaps)
    assert all(a[1] < b[1] for a, b in zip(gaps, gaps[1:])), f"gap does not shrink as kappa decreases: {report}"
    assert gaps[0][1] < MAX_GAP_AT_SMALLEST_KAPPA, f"gap at the smallest kappa too large: {report}"


@pytest.mark.parametrize("material", ["Holzapfel", "Guccione"])
def test_p2p1_matches_t10_at_small_kappa(binary, cm_env, tmp_path, material):
    """T10 uses the law's full stress, P2P1 its isochoric stress plus the pressure field, so the two
    agree at small kappa only if the isochoric stress is the law's stress minus its volumetric part.
    Holzapfel's volumetric energy is kappa/4 (J^2 - 1 - 2 ln J) rather than the kappa/2 (J - 1)^2 of
    the perturbed constraint; the two differ at third order in J - 1, far below this tolerance."""
    pytest.importorskip("meshio")
    gap, pid = _gap_to_t10(binary, cm_env, tmp_path, KAPPA_SWEEP[0], material)
    assert gap < MAX_GAP_AT_SMALLEST_KAPPA, f"{material}: P2P1 differs from T10 by {gap:.2e} at PointID={pid}"
